source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'VIPERS-Wireframe-Protocol_Example', :exclusive => true do
  pod 'VIPERS-Wireframe-Protocol', :path => '../'
end

target 'VIPERS-Wireframe-Protocol_Tests', :exclusive => true do
  pod 'VIPERS-Wireframe-Protocol', :path => '../'

  
end
